import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type {Metadata} from "next";
import {Inter, Noto_Sans_JP, Oswald} from 'next/font/google'
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const notojp = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-noto-sans-jp',
});

const oswald = Oswald({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: '--font-oswald',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${inter.variable} ${notojp.variable} ${oswald.variable}`}>
    <body className="bg-white">
    <Header/>
    <div className="min-h-screen">
      {children}
    </div>
    <Footer/>
    </body>
    </html>
  );
}
